ai_vedio_gen_default_fun: openai_gen
ai_vedio_openai_url: https://api.agnes-ai.cn/v1/videos
ai_vedio_openai_key: xxx
ai_vedio_openai_model: agnes-image-2.5-flash

# tmpfiles.org/file.io/transfer.sh/Cloudflare R2/aliyun/aliyun_oss/aliyun-oss
TEMP_OSS: tmpfiles.org
ALIYUN_TEMP_OSS_BUCKET: xxx
ALIYUN_TEMP_OSS_REGION: cn-beijing

ALIYUN_TEMP_OSS_ACCESS_KEY_ID: xxx
ALIYUN_TEMP_OSS_ACCESS_KEY_SECRET: xxx

ALIYUN_TEMP_OSS_PREFIX: temp/vedio_gen
ALIYUN_TEMP_OSS_EXPIRES_SECONDS: 1800